### ISSUE TITLE
不小心将betterncm的按钮删除后要怎样回到设置界面还原回来呢，在根目录里删除再重新下载还是不会清空设置 仍然在重载插件后 那个按钮又消失不见，能否还原回默认初始设置呢?

### ISSUE THREAD

**Issue by YUYAN12138MG** [BetterNCM/TinyNCM#4]

**Comment by z2362723275** [comment]
我也一样，兄弟你解决没

**Comment by tomingqiao** [comment]
我也差不多，我手欠写了个body上去，整个网易云音乐直接变白了😵

**Comment by std-microblock** [comment]
在 TinyNCM 1.0.3 后，可以使用快捷键 Ctrl-Alt-F3 清除规则

在以前的版本，可以按下 F12，切换到 Application 栏，选择 LocalStorage - orpheus 并删除 cc.microblock.betterncm.tinyncm.custom 与 cc.microblock.betterncm.tinyncm.minify 两项

**Comment by LSDGQ** [comment]
> 在 TinyNCM 1.0.3 后，可以使用快捷键 Ctrl-Alt-F3 清除规则
> 
> 在以前的版本，可以按下 F12，切换到 Application 栏，选择 LocalStorage - orpheus 并删除 cc.microblock.betterncm.tinyncm.custom 与 cc.microblock.betterncm.tinyncm.minify 两项

感谢，大佬救命
